baseURL = "https://github.com/mattconfusion"
languageCode = "it"
title = "LLHR"
theme = "hyde"
enableGitInfo = true

[params]
    description = "Labyrinth Lord House Rules"
    copyright = "Matt Confusion"
    custom_css = ["fonts/firacode/fira_code.css"]

