baseURL = "https://mattconfusion.github.io/LLHR"
languageCode = "it"
theme = "hyde"
enableGitInfo = true

title = "llhr"
[params]
    description = "Labyrinth Lord House Rules"
    copyright = "© Matt Confusion"
    custom_css = ["css/style.css"]

